### ISSUE TITLE
Review CartoCSS material images

### ISSUE THREAD

**Issue by jsanz** [CartoDB/carto-workshop#35]

**Comment by ramiroaznar** [comment]
Hey @jsanz I have fixed [fundamentals](https://github.com/CartoDB/carto-workshop/blob/master/03-cartography/resources/cartocss.md) section. But I do not know why the imgs from [basics](https://github.com/CartoDB/carto-workshop/blob/master/03-cartography/resources/basics.md) do not work. Even using urls, instead of the path.

**Comment by jsanz** [comment]
On Mon, Feb 13, 2017 at 5:26 PM, Ramiro Aznar <notifications@github.com>
wrote:

> Hey @jsanz <https://github.com/jsanz> I have fixed fundamentals
> <https://github.com/CartoDB/carto-workshop/blob/master/03-cartography/resources/cartocss.md>
> section. But I do not know why the imgs from basics
> <https://github.com/CartoDB/carto-workshop/blob/master/03-cartography/resources/basics.md>
> do not work. Even using urls, instead of the path.
>
>
> That's because the url needs to be relative to work as expected:

![category](../exercises/img/category.png)
